package com.example.soul_knight_save_editor.unlock

data class ItemKey(val field: String, val id: String)
enum class ItemKind { TAPE, QUANTITY, AMOUNT, BLUEPRINT, FACILITY, JEWELRY }
data class ItemDefinition(val key: ItemKey, val label: String, val kind: ItemKind, val group: String)

/** Reviewed 8.6.0 IDs. Names come from the installed localization table and the 8.3/8.6 ID samples.
 * Contains no account identifiers, inventory quantities or full reference saves.
 * Ambiguous fusion particles, unknown tape names, activity materials and excluded fields are omitted.
 * This is a versioned allowlist, not a claim to cover every item in the game. */
object ItemCatalog {
    const val VERSION = 80600
    val entries: List<ItemDefinition> = listOf(
        ItemDefinition(ItemKey("materials", "material_tape_airbender_16"), "藏怒燎原", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_alien"), "超星际旅行", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_assassin_27"), "黯乐寅主", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_aurora"), "数码雷霆 #2", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_aurora_wrong_version"), "数码雷霆 #2 (Demo)", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_bgm_multi_room_skin_17"), "集结令", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_boss1"), "强手", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_boss2"), "劲敌", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_boss3"), "决战！", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_boss4"), "遗迹之战", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_boss_void"), "虚空降临", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_castle"), "英雄的化身", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_chess"), "王车易位进行曲", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_civilization"), "环球旅行序曲", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_dark"), "神秘大碟", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_defence"), "直到黎明尽头", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_doctor_6"), "鼓—节奏之心", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_dragon_boy"), "祥瑞之境", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_easter"), "春天的礼物", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_elves_17"), "吉他—韵律之弦", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_end_temple"), "跪伏在神脚边", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_forest"), "勇闯密林深处", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_four_seasons"), "梦屿四季谣", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_grave"), "小心坠落！", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_graveyard"), "漆黑地牢", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_hall_cny"), "新春新气象", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_halloween"), "万圣节幽影", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_heroBall"), "数码空间", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_ice"), "冰风暴", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_icecave"), "地表下的秘密", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_irontide_multiroom"), "宕冢深处", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_island"), "钢铁破浪者永不沉没", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_joker_7"), "绮光旋乐", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_level_2g"), "联结主义万岁", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_level_4g"), "群峦之巅", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_monster"), "功成行满", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_mythology"), "逍遥乐", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_necromancer_16"), "键盘-和声之键", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_neon"), "数码雷霆 #1", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_ninja_6"), "怒烬灼华", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_opera"), "群英荟萃", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_party"), "落日余晖", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_rock_girl"), "星✦凛✦咲✦舞", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_ruins"), "远眺那辉煌的神庙", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_stars"), "星河之畔", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_stronghold_wave"), "茶歇时光", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_summer"), "夏天的味道", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_swamp"), "赞美诗", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_sword_master_4"), "贝斯—节拍之魂", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_thunderstorm"), "数码雷霆 #3", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_unrivaled_archenemy"), "争星夺月", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_volcano"), "翻滚的岩浆", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_warliege_12"), "哀唳穹宇", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_warlock_16"), "哀渡星河", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_tape_zhuazhua"), "数码雷霆 #4", ItemKind.TAPE, "磁带"),
        ItemDefinition(ItemKey("materials", "material_generic_weapon_fragment_0"), "白色通用武器进化碎片", ItemKind.QUANTITY, "通用进化碎片"),
        ItemDefinition(ItemKey("materials", "material_generic_weapon_fragment_1"), "绿色通用武器进化碎片", ItemKind.QUANTITY, "通用进化碎片"),
        ItemDefinition(ItemKey("materials", "material_generic_weapon_fragment_2"), "蓝色通用武器进化碎片", ItemKind.QUANTITY, "通用进化碎片"),
        ItemDefinition(ItemKey("materials", "material_generic_weapon_fragment_3"), "紫色通用武器进化碎片", ItemKind.QUANTITY, "通用进化碎片"),
        ItemDefinition(ItemKey("materials", "material_generic_weapon_fragment_4"), "橙色通用武器进化碎片", ItemKind.QUANTITY, "通用进化碎片"),
        ItemDefinition(ItemKey("materials", "material_generic_weapon_fragment_5"), "红色通用武器进化碎片", ItemKind.QUANTITY, "通用进化碎片"),
        ItemDefinition(ItemKey("materials", "material_battery"), "电池", ItemKind.QUANTITY, "材料"),
        ItemDefinition(ItemKey("materials", "material_cell"), "生物质", ItemKind.QUANTITY, "材料"),
        ItemDefinition(ItemKey("materials", "material_fertilize"), "肥料", ItemKind.QUANTITY, "材料"),
        ItemDefinition(ItemKey("materials", "material_fish"), "小鱼干", ItemKind.AMOUNT, "单独数量"),
        ItemDefinition(ItemKey("materials", "material_fragment_c6h8o6"), "维C机甲碎片", ItemKind.QUANTITY, "材料"),
        ItemDefinition(ItemKey("materials", "material_fragment_zulan"), "祖兰碎片", ItemKind.QUANTITY, "材料"),
        ItemDefinition(ItemKey("materials", "material_gear"), "零件", ItemKind.QUANTITY, "材料"),
        ItemDefinition(ItemKey("materials", "material_grain"), "宠物饲料", ItemKind.QUANTITY, "材料"),
        ItemDefinition(ItemKey("materials", "material_iron"), "铁矿", ItemKind.QUANTITY, "材料"),
        ItemDefinition(ItemKey("materials", "material_jewelry_fragment"), "通用图纸碎片", ItemKind.QUANTITY, "材料"),
        ItemDefinition(ItemKey("materials", "material_magic_black"), "魔法碎片 黑曜", ItemKind.QUANTITY, "材料"),
        ItemDefinition(ItemKey("materials", "material_magic_blue"), "魔法碎片 蓝", ItemKind.QUANTITY, "材料"),
        ItemDefinition(ItemKey("materials", "material_magic_cyan"), "魔法碎片 青", ItemKind.QUANTITY, "材料"),
        ItemDefinition(ItemKey("materials", "material_magic_green"), "魔法碎片 绿", ItemKind.QUANTITY, "材料"),
        ItemDefinition(ItemKey("materials", "material_magic_orange"), "魔法碎片 橙", ItemKind.QUANTITY, "材料"),
        ItemDefinition(ItemKey("materials", "material_magic_purple"), "魔法碎片 紫", ItemKind.QUANTITY, "材料"),
        ItemDefinition(ItemKey("materials", "material_magic_red"), "魔法碎片 红", ItemKind.QUANTITY, "材料"),
        ItemDefinition(ItemKey("materials", "material_ticket"), "普通角色试玩券", ItemKind.AMOUNT, "单独数量"),
        ItemDefinition(ItemKey("materials", "material_wood"), "木材", ItemKind.QUANTITY, "材料"),
        ItemDefinition(ItemKey("seeds", "plant_banboo_seed"), "竹子 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("seeds", "plant_binary_tree_seed"), "二叉树 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("seeds", "plant_blackrose_seed"), "黑玫瑰 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("seeds", "plant_cactus_seed"), "仙人掌 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("seeds", "plant_carrot_seed"), "萝卜 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("seeds", "plant_clivia_seed"), "君子兰 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("seeds", "plant_datura_seed"), "曼陀罗花 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("seeds", "plant_defend_flower_seed"), "守护花 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("seeds", "plant_dragon_tree_seed"), "火龙果树 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("seeds", "plant_eator_seed"), "食人花 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("seeds", "plant_fantastic_flower_seed"), "妙妙花 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("seeds", "plant_firecracker_seed"), "爆竹 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("seeds", "plant_flatpeach_seed"), "蟠桃 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("seeds", "plant_gear_flower_seed"), "齿轮花 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("seeds", "plant_gem_flower_seed"), "宝石花 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("seeds", "plant_gem_tree_seed"), "宝石树 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("seeds", "plant_ginseng_seed"), "人参 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("seeds", "plant_heptacolor_seed"), "七色堇 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("seeds", "plant_icepear_seed"), "冻梨 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("seeds", "plant_iron_tree_seed"), "铁树 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("seeds", "plant_lavender_seed"), "薰衣草 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("seeds", "plant_lithiumflower_seed"), "锂之花 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("seeds", "plant_lotus_seed"), "天山雪莲 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("seeds", "plant_lycoris_seed"), "曼珠沙华 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("seeds", "plant_magic_flower_seed"), "魔力花 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("seeds", "plant_mandrake_seed"), "曼德拉草 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("seeds", "plant_mirror_plane_flower_seed"), "镜面花 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("seeds", "plant_monotropa_seed"), "水晶兰 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("seeds", "plant_mushroom_gold_seed"), "黄金蘑菇 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("seeds", "plant_mushroom_seed"), "水晶蘑菇 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("seeds", "plant_nepenthes_seed"), "猪笼草 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("seeds", "plant_pumpkin_seed"), "南瓜 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("seeds", "plant_qilixiang_seed"), "七里香 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("seeds", "plant_radar_seed"), "雷达花 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("seeds", "plant_rainbow_grass_seed"), "彩虹草 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("seeds", "plant_roselle_seed"), "洛神葵 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("seeds", "plant_rosemary_seed"), "迷迭香 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("seeds", "plant_shallot_seed"), "大葱 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("seeds", "plant_silver_poplar_seed"), "银白杨 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("seeds", "plant_strange_flower_seed"), "奇异花 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("seeds", "plant_tree_seed"), "橡树 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("seeds", "plant_trumpet_seed"), "蓝藻花 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("seeds", "plant_vine_seed"), "藤蔓 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("seeds", "plant_watermelon_seed"), "西瓜 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("seeds", "plant_worm_seed"), "冬虫夏草 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("seeds", "plant_xmas_seed"), "圣诞树 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("seeds", "plant_zongzi_seed"), "粽子花 · 种子", ItemKind.QUANTITY, "种子"),
        ItemDefinition(ItemKey("tokenTickets", "token_equipment_none_0"), "装备兑换券（具体用途待核）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_ARAM_5"), "因子兑换券 · ARAM", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_AggressiveEnemy_5"), "敌人更具有攻击性 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_AllAlone_5"), "不能携带宠物及佣兵 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_Artifacts_5"), "因子兑换券 · Artifacts", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_BadLuck_5"), "坏运气 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_Badass_5"), "因子兑换券 · Badass", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_BlackFog_5"), "瘴气弥漫 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_Blessing_5"), "因子兑换券 · Blessing", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_BombGift_5"), "普通怪物房间奖励宝箱(白箱子)只会出现金币或炸弹 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_BoomBoomBoom_5"), "爆爆爆 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_BoxMutation_5"), "箱子突变 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_CharFactor_5"), "因子兑换券 · CharFactor", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_ComboGun_5"), "因子兑换券 · ComboGun", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_Cruel_5"), "暴击伤害增加 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_Curse_5"), "因子兑换券 · Curse", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_Dark_5"), "视野受限 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_Dejavu_5"), "既视感 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_DoubleBoss_5"), "你将同时面对两个首领，但首领会变得更弱一些 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_DoubleCd_5"), "技能冷却时间变成2倍 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_DoubleCritic_5"), "武器的暴击率加倍，暴击伤害减半 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_Endurance_5"), "因子兑换券 · Endurance", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_EnemyBuffImmune_5"), "敌人所受负面效果时间减半 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_EnemyDefence_5"), "敌人防御+1 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_EnemyDoubleHp_5"), "敌人拥有双倍血量 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_EnemyFlash_5"), "敌人受到伤害后会瞬移 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_EnemySplit_5"), "怪物血量少于一半时会分裂 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_ExEnemy_5"), "精英怪物出现概率增加 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_Exception_5"), "角色受到攻击时会被附加随机异常状态，冷却时间5秒 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_ExtraHurtDamage_5"), "角色受到的伤害+1，怪物受到的伤害+2（可获取10次） · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_FastEnemyBullet_5"), "敌人子弹速度增加 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_FastEnemy_5"), "敌人变快，但是偶尔会眩晕 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_FastShooter_5"), "武器的攻击速度加倍，但攻击力减半 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_FloorCrack_5"), "时空裂隙 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_Frozen_5"), "因子兑换券 · Frozen", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_FullHouse_5"), "每关都能额外遇到一个特殊房间 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_FusionWeaponActivity_5"), "因子兑换券 · FusionWeaponActivity", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_GainMount_5"), "每进入一个新场景可以获得一个坐骑 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_GainWeapon_5"), "每进入一个新场景可以获得一把武器 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_GoodLuck_5"), "好运气 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_HalfCd_5"), "技能冷却时间减少50% · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_HardShield_5"), "战斗中护盾不会恢复,但拥有更强的防御力 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_HugePet_5"), "宠物极巨化，拥有更高的攻击力和攻击性 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_Huge_5"), "角色体型变大 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_IncreaseEnemyBuffImmune_5"), "增加怪物对控制效果的免疫增强（可获取10次） · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_InferiorMedicine_5"), "劣质药剂 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_InfiniteEnergy_5"), "拥有无限能量 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_Inflation_5"), "地牢商品价格加倍 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_Intensive_5"), "敌人更加密集 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_IronTide_5"), "因子兑换券 · IronTide", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_ItIsFate_5"), "命中注定 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_KillEnemyRebornTeammate_5"), "击杀怪物有概率复活全体队友 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_LackEnergy_5"), "最大能量减半 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_LackHp_5"), "生命上限固定为1点 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_LessBuff_5"), "减少1个天赋位置，选择天赋时增加1个选项 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_LessChoice_5"), "增加1个天赋位置，选择天赋时减少1个选项 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_LongMap_5"), "增加地牢中房间的数量 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_Loop_5"), "因子兑换券 · Loop", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_MelleOnly_5"), "只能使用近战武器 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_MelleWeaken_5"), "近战武器无法消除敌人子弹 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_MeridianDisorder_5"), "经脉错乱 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_Might_5"), "因子兑换券 · Might", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_MonsterAircraft_5"), "怪物飞艇 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_MoreBrave_5"), "越战越勇 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_MoreBuff_5"), "额外获得3个天赋位置 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_MoreChoice_5"), "选择天赋时增加2个选项 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_MoreGeneEnemy_5"), "基因怪出现的概率+2%（可获取10次） · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_MultiStatue_5"), "可以同时拥有多个雕像效果 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_OneWeapon_5"), "默认只能携带一把武器 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_Painless_5"), "功能性界面失去作用 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_Psyche_5"), "因子兑换券 · Psyche", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_RandomCharactor_5"), "进入下一层时随机更换所选角色 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_RebornTwice_5"), "增加复活次数 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_ReduceEnemyBuffImmune_5"), "抵消一层威压值对控制效果的免疫增强（可获取10次） · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_ReduceEnemyMoveSpeed_5"), "怪物移动速度 -1%(可获取10次) · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_ReforgeWeapon_5"), "每关开始时会重铸手上的武器 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_RenduErmai_5"), "经脉畅通 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_SaleDay_5"), "特卖日 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_SleepWalking_5"), "地牢顺序被打乱 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_SlowShooter_5"), "武器的攻击力加倍，但攻击速度减半 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_SpaceDistortion_5"), "扭曲空间 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_Tenacious_5"), "生命值低于50%时自动恢复 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_TimeDistortion_5"), "时间流速不稳定 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_TimeRacing_5"), "在限时内通关1次游戏 （普通{0}分钟，炸天{1}分钟） · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_Tiny_5"), "角色体型变小 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_TopWanted_5"), "红色通缉令 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_Tower_5"), "因子兑换券 · Tower", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_TrackingLaser_5"), "跟踪激光 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_Troop_5"), "因子兑换券 · Troop", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_VolcanoEruption_5"), "因子兑换券 · VolcanoEruption", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_WeaponEquip_5"), "所有武器自带一个配件 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_WeaponOverheating_5"), "武器过热 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_factor_WrongConfig_5"), "配置错误 · 因子兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_hero"), "英雄角色试玩券", ItemKind.AMOUNT, "单独数量"),
        ItemDefinition(ItemKey("tokenTickets", "token_seed_none_0"), "种子兑换券（内部后缀0）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_seed_none_1"), "种子兑换券（内部后缀1）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_seed_none_2"), "种子兑换券（内部后缀2）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_seed_none_3"), "种子兑换券（内部后缀3）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_seed_none_4"), "种子兑换券（内部后缀4）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_seed_none_5"), "种子兑换券（内部后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_none_0"), "因子兑换券 · token_weapon_none_0", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_none_1"), "因子兑换券 · token_weapon_none_1", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_none_2"), "因子兑换券 · token_weapon_none_2", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_none_3"), "因子兑换券 · token_weapon_none_3", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_none_4"), "因子兑换券 · token_weapon_none_4", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_none_5"), "因子兑换券 · token_weapon_none", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_028_4"), "雪狐 土豪金 · 武器兑换券（后缀4）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_067_0"), "刺剑 · 武器兑换券（后缀0）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_095_5"), "盾牌 · 武器兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_113_4"), "精致法杖 · 武器兑换券（后缀4）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_128_5"), "火龙步枪 · 武器兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_135_5"), "一拳 · 武器兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_184_3"), "次次次时代冲锋枪 · 武器兑换券（后缀3）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_195_0"), "登山杖 · 武器兑换券（后缀0）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_239_1"), "人民冲锋枪 · 武器兑换券（后缀1）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_240_5"), "妙妙枪 · 武器兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_245_5"), "光剑 土豪金 · 武器兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_246_4"), "雷剑 · 武器兑换券（后缀4）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_247_4"), "群星之弓 · 武器兑换券（后缀4）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_254_5"), "阿努比斯的权杖 · 武器兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_25hammer_5"), "二五仔之锤 · 武器兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_268_4"), "重铸的圣剑 · 武器兑换券（后缀4）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_274_4"), "天堂之拳 · 武器兑换券（后缀4）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_280_4"), "烤激光鱼 · 武器兑换券（后缀4）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_288_5"), "黄金狙击步枪 · 武器兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_289_5"), "黄金狙击枪专业版 · 武器兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_316_3"), "床子弩 · 武器兑换券（后缀3）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_330_2"), "脉冲 · 武器兑换券（后缀2）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_343_3"), "激光雨 · 武器兑换券（后缀3）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_347_3"), "飓风拳套 · 武器兑换券（后缀3）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_356_5"), "暗红小鬼 · 武器兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_357_5"), "女皇之触 · 武器兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_358_5"), "女皇之抚 · 武器兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_359_5"), "至尊权杖 · 武器兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_360_5"), "千束 · 武器兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_361_5"), "宁神 · 武器兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_362_5"), "风眼 · 武器兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_363_5"), "岩祖大哥大 · 武器兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_365_3"), "“棒棒糖” · 武器兑换券（后缀3）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_366_4"), "光之书 · 武器兑换券（后缀4）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_367_4"), "暗之书 · 武器兑换券（后缀4）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_371_4"), "海盗王舰炮 · 武器兑换券（后缀4）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_372_4"), "魔导师之杖 · 武器兑换券（后缀4）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_373_5"), "小木筒 · 武器兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_374_5"), "巨型枫叶 · 武器兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_375_5"), "元素石双刀 · 武器兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_376_5"), "40米长刀40米长刀 · 武器兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_377_5"), "八分饱加特林 · 武器兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_378_5"), "激裂 · 武器兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_379_5"), "聚爆极冰 · 武器兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_380_5"), "老铁的锤子 · 武器兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_381_5"), "传奇焊枪 · 武器兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_382_5"), "咒术之杖 · 武器兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_383_5"), "粽叶枪 · 武器兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_384_5"), "诅咒圣杯 · 武器兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_385_5"), "修罗 · 武器兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_386_5"), "图标之笔 · 武器兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_387_5"), "卡顿激光枪 · 武器兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_400_4"), "风暴战斧 · 武器兑换券（后缀4）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_banana_5"), "香蕉 · 武器兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_boss_year_beast_5"), "超级火箭礼花 · 武器兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("tokenTickets", "token_weapon_weapon_coop_tennis_5"), "网球拍 · 武器兑换券（后缀5）", ItemKind.QUANTITY, "兑换券"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_006"), "强力分裂者 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_007"), "雪狐 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_008"), "大雪狐 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_009"), "巨雪狐 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_010"), "沙漠之鹰 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_015"), "左轮手枪 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_028"), "雪狐 土豪金 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_033"), "魅影 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_034"), "冰川 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_038"), "骑士之拳 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_041"), "加特林 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_043"), "火箭炮 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_044"), "聚爆 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_050"), "守卫者 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_061"), "密集火箭发射器 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_064"), "柳叶刀 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_072"), "干草叉 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_076"), "三叉戟 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_078"), "火焰剑 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_079"), "冰霜剑 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_089"), "魔法弓 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_093"), "鱼 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_094"), "激光鱼 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_095"), "盾牌 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_097"), "足球 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_108"), "梦幻 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_111"), "火箭筒 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_115"), "自然法杖 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_120"), "咖喱棒 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_121"), "网瘾少年 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_122"), "大猿长弓 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_127"), "晶蟹钛刀 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_128"), "火龙步枪 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_129"), "红龙机枪 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_131"), "沙虫 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_132"), "瓦克恩冲锋枪 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_134"), "食人花 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_135"), "一拳 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_139"), "连射霰弹枪 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_140"), "樱花霰弹枪 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_141"), "轰炸机 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_146"), "拔粪宝 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_156"), "织网者 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_159"), "多弹头导弹 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_160"), "黑洞导弹 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_161"), "尚方宝剑 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_170"), "冰与火之鹰 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_175"), "雪人之鹰 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_181"), "强化突击步枪 + · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_183"), "榴弹手枪 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_192"), "木锤 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_200"), "网瘾少女 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_207"), "重型猎斧 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_210"), "浪潮法杖 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_215"), "国王的新枪 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_220"), "爆炸弩 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_223"), "绿色的盆 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_224"), "电弧手里剑 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_231"), "地下水(崭新出厂) · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_233"), "闹肚子的彩虹马 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_239"), "人民冲锋枪 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_243"), "大巫师的旧法杖 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_246"), "雷剑 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_260"), "布朗线圈炮 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_270"), "养剑葫 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_274"), "天堂之拳 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_275"), "花言巧语 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_277"), "流星 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_278"), "羊叫兽 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_302"), "巨巨雪狐 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_306"), "金蟹战锤 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_307"), "黑暗大骑士的剑 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_309"), "量子手里剑 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_310"), "陌刀 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_311"), "宙斯之矛 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_315"), "超级散弹枪 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_316"), "床子弩 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_317"), "暗黑低语匕首 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_320"), "痛苦面具 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_323"), "死神之息 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_326"), "冰爆 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_327"), "灰狐 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_329"), "起爆苦无 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_330"), "脉冲 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_343"), "激光雨 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_345"), "玄冥 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_346"), "便携炸弹工厂 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_366"), "光之书 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_367"), "暗之书 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_370"), "边塞重弩 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_371"), "海盗王舰炮 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_372"), "魔导师之杖 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_374"), "巨型枫叶 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_376"), "40米长刀40米长刀 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_377"), "八分饱加特林 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_399"), "台球杆 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_400"), "风暴战斧 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_401"), "键盘侠 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_402"), "美杜莎之瞳 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_403"), "金箍棒 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_404"), "闪电五连鞭 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_405"), "元碎牙 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_406"), "普拉萨莫尼克 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_411"), "种子枪 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_412"), "五子棋盘 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_413"), "元气弹发射器 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_414"), "红色恶魔角 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_415"), "怪物压缩器 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_evolution_weapon_cg_2"), "飞熊军激光炮 · 武器进化蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_m_mech_2"), "天启 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_m_mech_3"), "维C装甲 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_m_mech_4"), "信号增幅器 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_m_mech_5"), "舞狮装甲 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_m_mech_6"), "飞梭战机 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_m_mech_7"), "幽浮51 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_m_mech_8"), "狱火战车 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_m_mech_9"), "独角仙 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_m_mech_coin"), "财迷 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_m_mecha_normal_2s"), "吉光片羽 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_m_mecha_normal_b"), "爆裂装甲 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_m_mecha_normal_d"), "突击装甲 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_m_mecha_normal_e"), "游击装甲 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_room_decorate_drink_seller"), "blueprint_room_decorate_drink_seller", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_room_decorate_fishbowl"), "blueprint_room_decorate_fishbowl", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_room_decorate_magic_well"), "blueprint_room_decorate_magic_well", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_room_decorate_mysteriou_statue"), "blueprint_room_decorate_mysteriou_statue", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_skill_Druid_1"), "剧毒藤蔓 · 技能蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_skill_Officer_2"), "空中支援 · 技能蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_skill_Paladin_2"), "爆裂飞盾 · 技能蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_skill_Priest_1"), "祈祷 · 技能蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_skill_Viking_2"), "跳跃 · 技能蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_skill_Warlock_1"), "协力：艾利欧格 · 技能蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_skin_alchemist_14"), "哭哭柠 · 皮肤蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_skin_alchemist_8"), "包青天 · 皮肤蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_skin_elves_6"), "{boss07} · 皮肤蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_skin_elves_9"), "黄忠 · 皮肤蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_skin_engineer_8"), "皇天 · 皮肤蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_skin_knight_20"), "苍蝇座 · 皮肤蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_skin_mage_7"), "大巫师 皮肤 · 皮肤蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_skin_necromancer_1"), "彩蛋兔皮肤 · 皮肤蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_skin_necromancer_13"), "小幽 · 皮肤蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_skin_necromancer_6"), "新月 · 皮肤蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_skin_officer_5"), "{boss23} · 皮肤蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_skin_paladin_12"), "人鱼统领 · 皮肤蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_skin_paladin_7"), "{boss01} · 皮肤蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_skin_priest_5"), "{boss18} · 皮肤蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_skin_ranger_12"), "老伙计 · 皮肤蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_skin_ranger_6"), "{bossshop} · 皮肤蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_skin_robot_12"), "摩艾石像 · 皮肤蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_skin_robot_6"), "女娲 · 皮肤蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_skin_taoist_5"), "{boss08} · 皮肤蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_skin_taoist_6"), "鬼鬼祟祟的魔术师 · 皮肤蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_skin_trapmaster_4"), "厚礼 · 皮肤蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_skin_vampire_7"), "{boss15} · 皮肤蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_skin_viking_19"), "岩祖 皮肤 · 皮肤蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_skin_viking_4"), "无头骑士 皮肤 · 皮肤蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_skin_viking_6"), "思 · 皮肤蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_skin_werewolf_9"), "{boss10} · 皮肤蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_transform_weapon_beheaded"), "细胞凝液 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_transform_weapon_envoy"), "回响琥珀 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_transform_weapon_ninja"), "超时空忍者召唤器 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_transform_weapon_specialforces"), "特别支援呼叫器 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_transform_weapon_transcendent"), "维度指引手册 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_184"), "次次次时代冲锋枪 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_188"), "圆盾 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_189"), "爪子 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_195"), "登山杖 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_211"), "无尽生命药水 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_212"), "无尽能量药水 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_213"), "无尽恢复药水 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_217"), "撒币枪 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_220000"), "blueprint_weapon_220000", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_223"), "绿色的盆 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_224"), "电弧手里剑 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_237"), "超级科学计算器 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_238"), "素颜相机 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_240"), "妙妙枪 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_242"), "箱子 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_252"), "超级大宝贝儿 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_294"), "漫游左轮 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_321"), "电钻 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_333"), "迷你骑士手办 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_340"), "超级怪兽卡牌 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_341"), "少年勇者魔杖 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_342"), "英雄王剑 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_344"), "苍龙魔杖 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_356"), "暗红小鬼 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_370"), "边塞重弩 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_373"), "小木筒 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_380"), "老铁的锤子 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_381"), "传奇焊枪 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_383"), "粽叶枪 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_385"), "修罗 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_386"), "图标之笔 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_387"), "卡顿激光枪 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_392"), "走音麦克风 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_393"), "神秘商贩之枪 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_394"), "40厘米直尺 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_395"), "超厚辞典 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_396"), "全能发球器 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_397"), "脏脏的调色盘 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_398"), "熔核之弓 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_407"), "假发 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_408"), "Bug发射器 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_409"), "甜蜜蜜奶茶 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_411"), "种子枪 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_413"), "元气弹发射器 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_415"), "怪物压缩器 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_416"), "刀刀烈火 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_bossrushfinal"), "封灵战锤 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_bossrushfinalA"), "魂刃:英魂 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_bossrushfinalB"), "魂刃:魔魂 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_cg_0"), "黄巾军步枪 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_cg_1"), "陷阵营动能枪 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_cg_2"), "飞熊军激光炮 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_cg_3"), "青釭光剑 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_fel_fabric"), "邪能披风碎屑 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_fish_rod_a"), "手工鱼竿 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_fish_rod_b"), "普通鱼竿 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_fish_rod_c"), "中级鱼竿 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "blueprint_weapon_fish_rod_d"), "豪华鱼竿 · 蓝图", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "garden_skin_1"), "水帘洞露天庭院", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "garden_skin_2"), "观星领域-坠星坛", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "garden_skin_3"), "整装待渡", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "garden_skin_4"), "欧博士的制造厂", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "hall_skin_1"), "水帘洞府", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "hall_skin_2"), "《骑 土 之 家》", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "hall_skin_3"), "观星领域-议事厅", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "hall_skin_4"), "连环战船（壹）", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "hall_skin_5"), "欧博士的会客间", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "magic_area_skin_1"), "水帘洞神龛", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "magic_area_skin_2"), "观星领域-魔法场", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "magic_area_skin_3"), "连环战船（叁）", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "magic_area_skin_4"), "欧博士的实验室", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "mboar2"), "暴走野豬", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "mcristal"), "水晶虫", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "mspider"), "蜘蛛", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "multi_room_skin_1"), "一出好戏", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "multi_room_skin_10"), "据点：浪潮", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "multi_room_skin_11"), "欧博士的秘密基地", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "multi_room_skin_12"), "雷霆派对", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "multi_room_skin_13"), "通天河的故事", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "multi_room_skin_14"), "神谕圣殿", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "multi_room_skin_15"), "海风假日", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "multi_room_skin_16"), "练字时间", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "multi_room_skin_17"), "决战将至", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "multi_room_skin_18"), "龙之仙域", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "multi_room_skin_19"), "摇滚之夜", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "multi_room_skin_2"), "清云台", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "multi_room_skin_20"), "残局时廊", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "multi_room_skin_21"), "四季梦屿", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "multi_room_skin_3"), "失落祭坛", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "multi_room_skin_4"), "赤红的铸锻间", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "multi_room_skin_5"), "天台见", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "multi_room_skin_6"), "雪地矿山", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "multi_room_skin_7"), "作战会议", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "multi_room_skin_8"), "世界大观", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "multi_room_skin_9"), "终末圣殿", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "mvaken"), "瓦克恩", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "work_shop_skin_1"), "欧博士的维修站", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "work_shop_skin_2"), "水帘洞甲仗库", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "work_shop_skin_3"), "观星领域-造物所", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("blueprints", "work_shop_skin_4"), "连环战船（贰）", ItemKind.BLUEPRINT, "蓝图"),
        ItemDefinition(ItemKey("itemUnlock", "Motorcycle"), "摩托车", ItemKind.FACILITY, "设施"),
        ItemDefinition(ItemKey("itemUnlock", "plant_pot3"), "花圃槽位（内部编号3）", ItemKind.FACILITY, "设施"),
        ItemDefinition(ItemKey("itemUnlock", "plant_pot4"), "花圃槽位（内部编号4）", ItemKind.FACILITY, "设施"),
        ItemDefinition(ItemKey("itemUnlock", "plant_pot5"), "花圃槽位（内部编号5）", ItemKind.FACILITY, "设施"),
        ItemDefinition(ItemKey("itemUnlock", "plant_pot6"), "花圃槽位（内部编号6）", ItemKind.FACILITY, "设施"),
        ItemDefinition(ItemKey("itemUnlock", "plant_pot7"), "花圃槽位（内部编号7）", ItemKind.FACILITY, "设施"),
        ItemDefinition(ItemKey("jewelryData", "ArmorStunNecklace"), "金刚石护符", ItemKind.JEWELRY, "饰品"),
        ItemDefinition(ItemKey("jewelryData", "CritDamageRing"), "萤石戒指", ItemKind.JEWELRY, "饰品"),
        ItemDefinition(ItemKey("jewelryData", "DestroyBox"), "珠光宝匣", ItemKind.JEWELRY, "饰品"),
        ItemDefinition(ItemKey("jewelryData", "EatEnemy"), "飞廉头骨", ItemKind.JEWELRY, "饰品"),
        ItemDefinition(ItemKey("jewelryData", "EnergyHealthRing"), "翠玉戒指", ItemKind.JEWELRY, "饰品"),
        ItemDefinition(ItemKey("jewelryData", "EnergyRegen"), "金如意", ItemKind.JEWELRY, "饰品"),
        ItemDefinition(ItemKey("jewelryData", "FirePoisonNecklace"), "火焰魔骸骨", ItemKind.JEWELRY, "饰品"),
        ItemDefinition(ItemKey("jewelryData", "IcyRing"), "冰霜指环", ItemKind.JEWELRY, "饰品"),
        ItemDefinition(ItemKey("jewelryData", "KillBoss"), "食人魔獠牙", ItemKind.JEWELRY, "饰品"),
        ItemDefinition(ItemKey("jewelryData", "PetDefenceTalisman"), "狼痕铁符", ItemKind.JEWELRY, "饰品"),
        ItemDefinition(ItemKey("jewelryData", "ProjectileDamageTotem"), "巫族图腾", ItemKind.JEWELRY, "饰品"),
        ItemDefinition(ItemKey("jewelryData", "ReplaceWeapon"), "焚烬", ItemKind.JEWELRY, "饰品"),
        ItemDefinition(ItemKey("jewelryData", "ShieldDamageBadge"), "十字军章", ItemKind.JEWELRY, "饰品"),
        ItemDefinition(ItemKey("jewelryData", "SkillEnhance"), "青玉项链", ItemKind.JEWELRY, "饰品"),
        ItemDefinition(ItemKey("jewelryData", "SpeedDamageRing"), "飞羽指环", ItemKind.JEWELRY, "饰品")
    )
    val byKey = entries.associateBy { it.key }
    fun ofKind(kind: ItemKind) = entries.filter { it.kind == kind }
}
