package com.example.soul_knight_save_editor.unlock

/** 8.6.0 candidate order from docs/pet-mapping-8.6.0.md. Hide (17) has no official name and is excluded. */
data class PetDefinition(val index: Int, val id: String, val label: String)

object PetCatalog {
    val entries = listOf(
        PetDefinition(0, "Cat", "阿凉"),
        PetDefinition(1, "Dog", "旺财"),
        PetDefinition(2, "Pig", "火腿"),
        PetDefinition(3, "Slime", "蓝色史莱姆"),
        PetDefinition(4, "Robot", "萝卜卜"),
        PetDefinition(5, "Panda", "熊猫"),
        PetDefinition(6, "Rabbit", "蹦蹦"),
        PetDefinition(7, "CanPig", "罐头猪"),
        PetDefinition(8, "TapTap", "嗒普"),
        PetDefinition(9, "Pet4399", "豆娃"),
        PetDefinition(10, "Gugu", "鸽子"),
        PetDefinition(11, "Owl", "扑扑"),
        PetDefinition(12, "Seal", "海豹宝宝"),
        PetDefinition(13, "Bug", "祖传漏洞"),
        PetDefinition(14, "Bat", "来福"),
        PetDefinition(15, "Hippo", "粉红小河马"),
        PetDefinition(16, "Tengo", "小天狗"),
        PetDefinition(18, "Pug", "阿巴"),
        PetDefinition(19, "Corgi", "黑麦"),
        PetDefinition(20, "Cat1", "冷喵"),
        PetDefinition(21, "Cat2", "雪诺"),
        PetDefinition(22, "Rabbit1", "趴趴"),
        PetDefinition(23, "Pig1", "牛仔"),
        PetDefinition(24, "LiangSir", "阿凉长官"),
        PetDefinition(25, "Blagny", "布拉尼"),
        PetDefinition(26, "Tortoise", "小兲"),
        PetDefinition(27, "Serenade", "夜歌"),
        PetDefinition(28, "Dog1", "太郎"),
        PetDefinition(29, "Cat3", "布丁"),
        PetDefinition(30, "Cat4", "泡泡"),
        PetDefinition(31, "Dog2", "波奇"),
        PetDefinition(32, "Dog3", "栗子"),
        PetDefinition(33, "dragon", "炎焱"),
        PetDefinition(34, "Cat5", "胡椒"),
        PetDefinition(35, "Cat6", "迷迭猫"),
        PetDefinition(36, "TenOff", "九折"),
        PetDefinition(37, "RushDuck", "冲鸭"),
        PetDefinition(38, "SacaSaca", "萨卡萨卡"),
        PetDefinition(39, "Cat7", "招财"),
        PetDefinition(40, "Hammer", "小锤锤"),
        PetDefinition(41, "Zongzi", "粽小子"),
        PetDefinition(42, "JiaoDirector", "胡椒导演"),
        PetDefinition(43, "FeatureBug", "进击的漏洞"),
        PetDefinition(44, "CoinPig", "财满满"),
        PetDefinition(45, "FireCat", "火力喵"),
        PetDefinition(46, "MiniSlime", "小史莱姆"),
        PetDefinition(47, "ZongziBro", "粽大哥"),
        PetDefinition(48, "Mahhmot", "土嚎"),
        PetDefinition(49, "Capybara", "小豚豚"),
        PetDefinition(50, "ShanghaiTower", "珍珠防御塔"),
        PetDefinition(51, "TrainerRobot", "小小教官"),
        PetDefinition(52, "FireSnowman", "火力雪人王"),
        PetDefinition(53, "ChillyGo", "凉块"),
        PetDefinition(54, "Nian", "来财"),
        PetDefinition(55, "CatMecha", "机甲阿凉"),
        PetDefinition(56, "EscapeMonkey", "小疯猴")
    )
}
