"""Generate numbered weapon names from an extracted 8.6.0 localization MonoBehaviour.

Usage: python tools/generate_weapon_catalog.py <extracted-localization.json>
The proprietary asset dump stays outside the repository.
"""
import argparse
import json
import re
from pathlib import Path

parser = argparse.ArgumentParser()
parser.add_argument("localization_json", type=Path)
args = parser.parse_args()
source = json.loads(args.localization_json.read_text(encoding="utf-8"))["mSource"]
language = next(i for i, entry in enumerate(source["mLanguages"]) if entry["Code"] == "zh-CN")
names = {}
for term in source["mTerms"]:
    match = re.fullmatch(r"weapon/(weapon_\d+)", term["Term"])
    if match:
        assert match[1] not in names and term["Languages"][language]
        names[match[1]] = term["Languages"][language]
assert len(names) == 416, "This generator is pinned to the investigated 8.6.0 resource."

def literal(text):
    return json.dumps(text, ensure_ascii=False).replace("$", r"\$")

lines = [
    "package com.example.soul_knight_save_editor.unlock", "",
    "/** Numbered IDs only, from 8.6.0 localization.ab zh-CN weapon/weapon_<digits> terms.",
    " * Resource SHA-256: dfa5677a2f9504fcce93c8da5c5b20063282dfe31a90caae92828dba257d6722",
    " * No guessed ID ranges. Existing non-numbered weapon counters are handled separately.",
    " * Generated by android/tools/generate_weapon_catalog.py. */",
    "object WeaponCatalog {", "    const val VERSION = 80600",
    '    private val idPattern = Regex("^weapon_[a-zA-Z0-9_]+$")',
    "    fun isWeaponId(id: String) = idPattern.matches(id)",
    "    val names: Map<String, String> = linkedMapOf(",
]
lines += [f"        {literal(key)} to {literal(names[key])}," for key in sorted(names, key=lambda value: int(value[7:]))]
lines += ["    )", "}", ""]
target = Path(__file__).resolve().parents[1] / "app/src/main/java/com/example/soul_knight_save_editor/unlock/WeaponCatalog.kt"
target.write_text("\n".join(lines), encoding="utf-8")
print(f"Generated {len(names)} weapon names: {target}")
